name = "JuliaOrgs"
uuid = "5a7b0bd1-ec30-44ab-97d9-d7f6aff89b81"
authors = ["Viral B. Shah <viral@mayin.org>"]
version = "0.1.0"

[deps]
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
